const express = require('express');
const cors = require('cors');
const routes = require('./routes');

const app = express();
app.use(cors());
app.use(express.json());
app.use(routes);

// ROTA / RECURSO

/*
    METODOS HTTP
    GET: BUSCAR/LISTAR UMA INFORMACAO NO BACKEND
    POST: CRIAR UMA INFORMACAO NO BACKEND
    PUT: ALTERAR UMA INFORMACAO NO BACKEND
    DELETE: REMOVER UMA INFORMACAO NO BACKEND

    TIPOS DE PARAMETROS
    QUERY PARAMS: PARAMETROS NOMEADOS ENVIADOS NA ROTA APOS '?' (FILTROS, PAGINACAO)
    ROUTE PARAMS: PARAMETROS UTILIZADOS PARA IDENTIFICAR RECURSOS
    REQUEST BODY: CORPO DA REQUISICAO, UTILIZADO PARA CRIAR OU ALTERAR RECURSOS

    BD
    SQL: MYSQL, SQLITE, POSTGRESQL, ORACLE, MICROSOFT SQL SERVER - SQLITE3
    NOSQL: MONGODB, COUCHDB, ETC

    DRIVER: SELECT * FROM USERS
    QUERY BUILDER: TABLE('USERS').SELECT('*').WHERE('') - KNEX <http://knexjs.org/>

*/


app.listen(3333);